name: Lint & Format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint with auto-fix
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --fix

      - name: Run Stylelint with auto-fix
        run: npx stylelint "**/*.{css,scss}" --fix

      - name: Run Prettier format
        run: npx prettier --write "**/*.{js,jsx,ts,tsx,css,scss,html,json,md}"
